### PR TITLE
build manifest with webpack publicPath

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by bertho-zero** [comment]
@thejameskyle it's related to https://github.com/thejameskyle/react-loadable/pull/84

**Comment by thejameskyle** [comment]
Why was `yarn.lock` updated?

**Comment by bertho-zero** [comment]
This is because I made a recent installation (`yarn`). If you prefer I can cancel?

**Comment by thejameskyle** [comment]
Yarn should not have rewritten the yarn.lock file so dramatically unless you deleted it or tried to change dependencies. Can you remove it from your commit?

**Comment by bertho-zero** [comment]
I removed it form the commit.

**Pull request merged**
