### PR TITLE
fix preloadReady

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by thejameskyle** [comment]
How is this fixing it?

**Comment by bertho-zero** [comment]
Without this fix I have this error:
image

And with this fix I have all the files that load, not just those concerned.

**Comment by thejameskyle** [comment]
Can you post exactly where in the react-loadable code that error is thrown? I can't tell from the stack trace because line numbers are based on your bundle.

**Comment by bertho-zero** [comment]
I do not have the error above, but on the other hand without this fix I have the following error:

```
Warning: Text content did not match. Server: "ChatSend" Client: "Loading"
```

Otherwise the rest works perfectly well, the reason why all my routes loaded is that all my `Loadable` were in the same file...

**Comment by thejameskyle** [comment]
> the reason why all my routes loaded is that all my Loadable were in the same file...

It shouldn't matter if they are all declared in the same file, it should only matter if they get rendered

**Comment by bertho-zero** [comment]
Now I do not have the same client-side rendering as server side, I have the loading components at first render in the client without this fix.

**Comment by thejameskyle** [comment]
I'm not sure why because this change does the exact opposite of what should be done. The updated test case is now incorrect behavior. Without an example of what you're doing I'm going to assume it is something wrong at your end and this just happens to fix it even if it introduces bad behavior.

**Pull request closed without merging**
