### PR TITLE
[WIP] pass params to loader (based on props)

### PR DESCRIPTION
**Pull request by debelbot**
Sometimes I've found I need to pass dynamic parameters to the loader, usually based on the props. This is useful because our component server can attach additional data to the component props.

If you agree with the general idea behind this PR, I'll be happy to polish it by writing tests and docs :)

### CODE REVIEW

**Comment by diruuu** [comment]
I need this.

**Comment by thejameskyle** [comment]
I'm not a fan of this. Your loader should be as static as possible or it's impossible to do things like server-side rendering reliably. I know that it is very limiting, but it's on purpose.

**Comment by dyst5422** [comment]
How then should we do something dynamic following the loading of a bundle?

ie replace redux reducer with new reducer from bundle prior to calling the render

**Comment by thejameskyle** [comment]
I don't know what that means but you can probably do it by overriding `opts.render`

```js
const LoadableComponent = Loadable({
  loader: () => import('./Foo'),
  loading: Loading,
  render(loaded, props) {
    return <loaded.default {...props}>;
  } 
});
```

**Comment by thejameskyle** [comment]
Why not just:

```js
const FancyHello = Loadable({ loader: () => import('./FancyHello'), ... });
const RegularHello = Loadable({ loader: () => import('./RegularHello'), ... });

const Hello = props =>
  props.name === 'Bob'
    ? <FancyHello {...props}/>
    : <RegularHello {...props}/>;
```

Doing a bunch of dynamic stuff within `import(...)` isn't even really supported by bundlers.

**Comment by thejameskyle** [comment]
I'm not interested in supporting that use case in this way

**Comment by dyst5422** [comment]
The case I am thinking about is like so

```ts
const Hello = Loadable({
  loader: (props) => import('./someModule').then(bundle => {
    props.reduxStore.replaceReducers(bundle.reducer);
    return bundle.component;
  },
  ...
});
```

It occurs to me now though that this sort of logic should probably live in `componentWillMount()`

**Comment by thejameskyle** [comment]
```js
const Hello = Loadable({
  loader: () => import('./someModule'),
  render(loaded, props) {
    props.reduxStore.replaceReducers(loaded.reducer);
    return loaded.component;
  }
});
```

**Comment by dyst5422** [comment]
That doesn't work because switching the reducers triggers a render...within a render. 

Definitely feel that `componentWillMount()` is the place for that kind of thing though.

```ts
const Hello = Loadable({
  loader: () => import('./someModule'),
  render(loaded, props) {
    props.reduxStore.replaceReducers(loaded.reducer);
    return <loaded.component reducer={loaded.reducer} {...props}/>;
  }
});

/*******************************/

class MyComponent extends React.Component {
  componentWillMount(props) {
    props.reduxStore.replaceReducers(props.reducer);
  }
...
}
```

**Comment by maubrsp** [comment]
@debelbot 

I think something like this may help

const Hello = props => {
 let Loader =Loadable({
  loader: () => import(props.name === 'Bob' ? './FancyHello' : './RegularHello'),
  ...
});
return (<Loader />)
}


 <Hello props={ something } />

**Comment by dbbk** [comment]
This would be useful for us! I just want to be able to retrieve routing params in the loader. Here's our code:

```js
loader: props => import('../components/AsyncComponent').then(module => {
  const ModuleComponent = module.default;

  if ('getInitialProps' in ModuleComponent) {
    return ModuleComponent.getInitialProps(props).then(resolvedProps => {
      return <ModuleComponent {...resolvedProps} />;
    });
  }

  return <ModuleComponent />;
}),
```

If there's a better way of accomplishing this I'd be grateful for suggestions.

**Comment by thejameskyle** [comment]
```js
Loadable({
  loader: () => import('../components/AsyncComponent'),
  render(module, props) {
    const ModuleComponent = module.default;

    if ('getInitialProps' in ModuleComponent) {
      return ModuleComponent.getInitialProps(props).then(resolvedProps => {
        return <ModuleComponent {...resolvedProps} />;
      });
    }

    return <ModuleComponent />;
  }
});
```

**Comment by dbbk** [comment]
@thejameskyle I don't think that'll work as `Loadable.render` won't allow you to return a promise?

**Comment by dekryptic** [comment]
@jamiebuilds Are you returning a `Promise` in render inside the if-statement? Is that permitted?

**Comment by jaybe78** [comment]
@dekryptic @dbbk @debelbot @maubrsp @dyst5422 @diruuu 
Hi Guys, I guess you've probably forked the project by now, and modify the repo according to your needs...
In al cases, may be we could think of a "good" solution to provided that functionality without hindering SSR.
Apparently the project has been abandoned, so I've forked the project and merged most important PRs there (migration to babel 7, webpack 4,...)
Check this out 
https://github.com/jaybe78/loadable-example/
https://www.npmjs.com/package/jaybe-react-loadable

**Comment by jaybe78** [comment]
@debel Yep right! does not support SSR yet though.

**Pull request closed without merging**
