### PR TITLE
docs: add reference to my question

### PR DESCRIPTION
**Pull request by kentcdodds**
In case anyone else is curious :)

ref #8

### CODE REVIEW

**Comment by Daniel15** [comment]
IMO you should add a summary of the contents of the issue, rather than just linking to it.  Perhaps an FAQ section?

**Comment by kentcdodds** [comment]
Especially now that issues are disabled 😅

**Comment by thejameskyle** [comment]
Added detail to the README

**Comment by mohsinulhaq** [comment]
issues page disabled :/

**Pull request closed without merging**
