### PR TITLE
Add TypeScript typings.

### PR DESCRIPTION
**Pull request by odensc**
Mostly copy-pasted from the Flow types with modifications for TypeScript syntax.

### CODE REVIEW

**Comment by thejameskyle** [comment]
This is now out of date

**Comment by odensc** [comment]
@thejameskyle Yeah, I've updated the ones on DefinitelyTyped instead. Thanks for the response anyway. :)

**Comment by joshgeller** [comment]
@odensc Just a heads up that the test file in DefinitelyTyped doesn't compile. I'd take a shot at fixing it but I'm super new to TypeScript.

**Comment by odensc** [comment]
@joshgeller Works for me... What's the error?

**Pull request closed without merging**
